//! Version catalog handling.
//!
//! GDK versions come from the community-maintained
//! `minecraft-windows-gdk-version-db` repository (GitHub / proxy / GitCode
//! mirrors); each entry carries the direct Microsoft Xbox Live CDN URLs of the
//! `.msixvc` package plus its MD5. UWP versions come from the raythnetwork DB.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::OnceLock;
use std::time::{Duration, Instant};

const GITHUB_URL: &str = "https://raw.githubusercontent.com/LiteLDev/minecraft-windows-gdk-version-db/refs/heads/main/historical_versions.json";
const PROXY_URL: &str = "https://github.bibk.top/LiteLDev/minecraft-windows-gdk-version-db/raw/refs/heads/main/historical_versions.json";
const GITCODE_URL: &str = "https://raw.gitcode.com/dreamguxiang/minecraft-windows-gdk-version-db/raw/main/historical_versions.json";
// Legacy UWP version DB: array of [version, updateId, type, architecture]
// (type: 0=Release, 1=Beta, 2=Preview). Plus a categorized TXT variant.
const UWP_DB_URL: &str = "https://www.raythnetwork.co.uk/versions.php?type=json";
const UWP_TXT_DB_URL: &str = "https://www.raythnetwork.co.uk/versions.php?type=txt";

/// UWP release dates (each package's Windows Update publish time), keyed by
/// UpdateID. Generated by `scripts/fetch-uwp-dates.mjs` from each package's FE3
/// `Last-Modified`; the UWP DB itself carries no dates. Refresh that file when
/// new UWP versions appear.
const UWP_DATES_JSON: &str = include_str!("uwp_dates.json");

fn uwp_dates() -> &'static HashMap<String, i64> {
    static MAP: OnceLock<HashMap<String, i64>> = OnceLock::new();
    MAP.get_or_init(|| serde_json::from_str(UWP_DATES_JSON).unwrap_or_default())
}

/// One downloadable Minecraft Bedrock version, normalized for the UI.
#[derive(Debug, Clone, Serialize)]
pub struct VersionItem {
    /// Full label as published, e.g. "Release 1.21.120.04".
    pub version: String,
    /// Short version without the type prefix, e.g. "1.21.120.04".
    pub short: String,
    /// "Release" or "Preview".
    pub kind: String,
    /// "GDK" (modern, .msixvc) or "UWP" (legacy, .appx).
    #[serde(rename = "packageType")]
    pub package_type: String,
    /// Direct CDN mirror URLs to the package (GDK only; UWP resolves via FE3).
    pub urls: Vec<String>,
    /// Windows Update UpdateID (UWP only; used to resolve a link via FE3).
    #[serde(rename = "updateId")]
    pub update_id: Option<String>,
    /// Publish time (unix seconds), if known.
    pub timestamp: Option<i64>,
    /// Expected MD5 of the package (uppercase hex in the DB; GDK only).
    pub md5: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct VersionCatalog {
    pub items: Vec<VersionItem>,
    /// Which mirror the catalog was fetched from.
    pub source: String,
}

/// Raw JSON entry shape from the version DB.
#[derive(Debug, Deserialize)]
struct RawEntry {
    version: String,
    #[serde(default)]
    urls: Option<Vec<String>>,
    #[serde(default)]
    url: Option<String>,
    #[serde(default)]
    timestamp: Option<i64>,
    #[serde(default)]
    md5: Option<String>,
}

#[derive(Debug, Deserialize)]
struct RawDb {
    #[serde(default, rename = "previewVersions")]
    preview: Vec<RawEntry>,
    #[serde(default, rename = "releaseVersions")]
    release: Vec<RawEntry>,
}

fn normalize_urls(entry: &RawEntry) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    if let Some(list) = &entry.urls {
        for u in list {
            let t = u.trim().trim_matches('`').to_string();
            if !t.is_empty() {
                out.push(t);
            }
        }
    }
    if out.is_empty() {
        if let Some(u) = &entry.url {
            let t = u.trim().trim_matches('`').to_string();
            if !t.is_empty() {
                out.push(t);
            }
        }
    }
    // Prefer the China CDN host first when present.
    out.sort_by_key(|u| if u.contains("xboxlive.cn") { 0 } else { 1 });
    out
}

fn map_entry(entry: RawEntry, kind: &str) -> VersionItem {
    let prefix = format!("{kind} ");
    let short = entry
        .version
        .strip_prefix(&prefix)
        .unwrap_or(&entry.version)
        .trim()
        .to_string();
    let urls = normalize_urls(&entry);
    VersionItem {
        version: entry.version.clone(),
        short,
        kind: kind.to_string(),
        package_type: "GDK".to_string(),
        urls,
        update_id: None,
        timestamp: entry.timestamp,
        md5: entry.md5,
    }
}

/// Fetch the full catalog: modern GDK versions + legacy UWP versions.
/// Resilient — if one source fails the other is still returned.
pub async fn fetch(prefer_cn: bool) -> Result<VersionCatalog, String> {
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(12))
        .user_agent(crate::USER_AGENT)
        .build()
        .map_err(|e| e.to_string())?;

    let (gdk, gdk_src) = match fetch_gdk(&client, prefer_cn).await {
        Ok(v) => v,
        Err(e) => (Vec::new(), format!("GDK failed: {e}")),
    };
    let uwp = fetch_uwp(&client).await.unwrap_or_default();

    let mut items = gdk;
    items.extend(uwp);

    if items.is_empty() {
        return Err(gdk_src);
    }

    // Modern GDK releases first, then legacy UWP; within each group newest first
    // by publish time, then by version.
    items.sort_by(|a, b| {
        let pa = u8::from(a.package_type != "GDK");
        let pb = u8::from(b.package_type != "GDK");
        pa.cmp(&pb)
            .then_with(|| b.timestamp.unwrap_or(0).cmp(&a.timestamp.unwrap_or(0)))
            .then_with(|| cmp_version_desc(&a.short, &b.short))
    });

    Ok(VersionCatalog {
        items,
        source: gdk_src,
    })
}

/// Fetch the modern GDK (.msixvc) catalog, trying mirrors in order.
async fn fetch_gdk(
    client: &reqwest::Client,
    prefer_cn: bool,
) -> Result<(Vec<VersionItem>, String), String> {
    let urls = if prefer_cn {
        [GITCODE_URL, PROXY_URL, GITHUB_URL]
    } else {
        [GITHUB_URL, PROXY_URL, GITCODE_URL]
    };

    let mut last_err = String::from("no mirrors tried");
    for url in urls {
        for attempt in 1..=2u8 {
            match client
                .get(url)
                .header("Accept", "application/json")
                .header("Cache-Control", "no-cache")
                .send()
                .await
            {
                Ok(resp) if resp.status().is_success() => match resp.text().await {
                    Ok(body) => match serde_json::from_str::<RawDb>(&body) {
                        Ok(db) => {
                            let mut items: Vec<VersionItem> = Vec::new();
                            for e in db.preview {
                                items.push(map_entry(e, "Preview"));
                            }
                            for e in db.release {
                                items.push(map_entry(e, "Release"));
                            }
                            return Ok((items, url.to_string()));
                        }
                        Err(e) => last_err = format!("decode {url}: {e}"),
                    },
                    Err(e) => last_err = format!("body {url}: {e}"),
                },
                Ok(resp) => last_err = format!("{url} attempt {attempt}: HTTP {}", resp.status()),
                Err(e) => last_err = format!("{url} attempt {attempt}: {e}"),
            }
        }
    }
    Err(last_err)
}

/// One parsed UWP catalog row before it becomes a VersionItem.
struct UwpRow {
    kind: String, // "Release" | "Preview" (Beta skipped — needs an MSA token)
    short: String,
    update_id: String,
    arch: String,
}

/// Map the numeric type column (0=Release, 1=Beta, 2=Preview) to a kind.
/// Returns None for Beta, which we skip (it requires a Microsoft-account token).
fn uwp_kind_from_type(t: &str) -> Option<&'static str> {
    match t.trim() {
        "0" => Some("Release"),
        "2" => Some("Preview"),
        _ => None,
    }
}

/// Convert a package moniker to a display version + architecture, e.g.
/// `Microsoft.MinecraftWindowsBeta_1.21.12020.0_x64__8wekyb...` -> ("1.21.120.20", "x64").
fn version_from_moniker(moniker: &str) -> Option<(String, String)> {
    let parts: Vec<&str> = moniker.split('_').collect();
    if parts.len() < 2 {
        return None;
    }
    let ver = parts[1];
    let arch = parts.get(2).copied().unwrap_or("x64").to_string();
    let comps: Vec<&str> = ver.split('.').collect();
    let display = if comps.len() == 4 {
        match (
            comps[0].parse::<u64>(),
            comps[1].parse::<u64>(),
            comps[2].parse::<u64>(),
        ) {
            // Internal packs patch+sub: 12020 -> 120.20
            (Ok(major), Ok(minor), Ok(raw)) => format!("{}.{}.{}.{}", major, minor, raw / 100, raw % 100),
            _ => ver.to_string(),
        }
    } else {
        ver.to_string()
    };
    Some((display, arch))
}

/// Parse the categorized TXT DB (sections: Releases / Beta / Preview; lines:
/// `<updateId> <moniker>`).
fn parse_txt_db(text: &str) -> Vec<UwpRow> {
    let mut out = Vec::new();
    let mut current = "Release";
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        match line {
            "Releases" => { current = "Release"; continue; }
            "Beta" => { current = "Beta"; continue; }
            "Preview" => { current = "Preview"; continue; }
            _ => {}
        }
        if current == "Beta" {
            continue; // needs MSA token
        }
        let mut parts = line.split(' ');
        let (Some(uid), Some(moniker)) = (parts.next(), parts.next()) else {
            continue;
        };
        if let Some((short, arch)) = version_from_moniker(moniker) {
            out.push(UwpRow {
                kind: current.to_string(),
                short,
                update_id: uid.to_string(),
                arch,
            });
        }
    }
    out
}

/// Fetch the legacy UWP catalog (Release + Preview) from the JSON DB
/// (`[version, updateId, type, arch]`) and the categorized TXT DB, merged by
/// UpdateID. Each version's download link is resolved later via FE3.
async fn fetch_uwp(client: &reqwest::Client) -> Result<Vec<VersionItem>, String> {
    let mut rows: Vec<UwpRow> = Vec::new();

    // JSON DB — read the type column (this is what was missing before).
    if let Ok(resp) = client.get(UWP_DB_URL).header("Accept", "application/json").send().await {
        if resp.status().is_success() {
            if let Ok(body) = resp.text().await {
                if let Ok(raw) = serde_json::from_str::<Vec<Vec<String>>>(&body) {
                    for r in raw {
                        if r.len() < 3 {
                            continue;
                        }
                        if let Some(kind) = uwp_kind_from_type(&r[2]) {
                            rows.push(UwpRow {
                                kind: kind.to_string(),
                                short: r[0].trim().to_string(),
                                update_id: r[1].trim().to_string(),
                                arch: r.get(3).map(|s| s.trim()).unwrap_or("x64").to_string(),
                            });
                        }
                    }
                }
            }
        }
    }

    // TXT DB — richer, section-categorized (gives more Preview entries).
    if let Ok(resp) = client.get(UWP_TXT_DB_URL).send().await {
        if resp.status().is_success() {
            if let Ok(text) = resp.text().await {
                rows.extend(parse_txt_db(&text));
            }
        }
    }

    if rows.is_empty() {
        return Err("no UWP rows".into());
    }

    let mut seen = std::collections::HashSet::new();
    let mut items = Vec::new();
    for r in rows {
        if r.short.is_empty() || r.update_id.is_empty() {
            continue;
        }
        // Keep x64 desktop builds; dedupe by UpdateID.
        if !r.arch.is_empty() && !r.arch.eq_ignore_ascii_case("x64") {
            continue;
        }
        if !seen.insert(r.update_id.clone()) {
            continue;
        }
        let timestamp = uwp_dates().get(&r.update_id).copied();
        items.push(VersionItem {
            version: format!("{} {}", r.kind, r.short),
            short: r.short,
            kind: r.kind,
            package_type: "UWP".to_string(),
            urls: Vec::new(),
            update_id: Some(r.update_id),
            timestamp,
            md5: None,
        });
    }
    Ok(items)
}

fn cmp_version_desc(a: &str, b: &str) -> std::cmp::Ordering {
    let pa: Vec<u64> = a.split('.').map(|x| x.parse().unwrap_or(0)).collect();
    let pb: Vec<u64> = b.split('.').map(|x| x.parse().unwrap_or(0)).collect();
    for i in 0..pa.len().max(pb.len()) {
        let va = pa.get(i).copied().unwrap_or(0);
        let vb = pb.get(i).copied().unwrap_or(0);
        if va != vb {
            return vb.cmp(&va);
        }
    }
    std::cmp::Ordering::Equal
}

#[derive(Debug, Clone, Serialize)]
pub struct MirrorResult {
    pub url: String,
    pub label: String,
    #[serde(rename = "latencyMs")]
    pub latency_ms: u128,
    pub ok: bool,
}

fn host_label(u: &str) -> String {
    u.split("://")
        .nth(1)
        .and_then(|rest| rest.split('/').next())
        .unwrap_or(u)
        .to_string()
}

/// Measure latency of each mirror with a HEAD request (matches `TestMirrorLatencies`).
pub async fn test_mirrors(urls: Vec<String>, timeout_ms: u64) -> Vec<MirrorResult> {
    let timeout_ms = if timeout_ms == 0 { 7000 } else { timeout_ms };
    let client = match reqwest::Client::builder()
        .timeout(Duration::from_millis(timeout_ms))
        .user_agent(crate::USER_AGENT)
        .build()
    {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };

    let mut results = Vec::with_capacity(urls.len());
    for u in urls {
        let start = Instant::now();
        let ok = match client.head(&u).send().await {
            Ok(resp) => {
                let s = resp.status().as_u16();
                (200..400).contains(&s)
            }
            Err(_) => false,
        };
        results.push(MirrorResult {
            label: host_label(&u),
            latency_ms: start.elapsed().as_millis(),
            ok,
            url: u,
        });
    }
    results
}
